name: Scheduled E2E
on:
  schedule:
    - cron: "55 8 * * 1-5"

defaults:
  run:
    working-directory: src/client

jobs:
  e2e:
    name: End-to-end test against uat

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        env:
          URL_PATH: https://web.uat.reactivetrader.com
          ENVIRONMENT: env
        run: |
          npm run e2e:web
