name: Tag build

on:
  push:
    tags:
      - v*

defaults:
  run:
    working-directory: src/client

env:
  BUCKET_WEB: reactive-trader-web-builds
  BUCKET_OPENFIN: reactive-trader-openfin-builds
  BUCKET_FINSEMBLE: reactive-trader-finsemble-builds
  BUCKET_LAUNCHER: reactive-trader-launcher-builds
  ENVIRONMENT: prod

jobs:
  build:
    name: Build & deploy

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node to v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set variables
        id: vars
        run: echo "tag=$(git describe --tag --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      - name: Install
        run: npm ci

      - name: Verify Quality (type checking, linting, format checking, tests)
        run: |
          npm run verify

      - name: Build (web)
        env:
          DOMAIN: https://web.prod.reactivetrader.com
          VITE_BUILD_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          npm run build
          npm run storybook:build

      - name: Deploy (web)
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r dist \
            gs://$BUCKET_WEB/tag/${{ steps.vars.outputs.tag }}

      - name: Build (OpenFin)
        env:
          DOMAIN: https://openfin.prod.reactivetrader.com
          VITE_BUILD_VERSION: ${{ steps.vars.outputs.tag }}
        run: npm run openfin:build

      - name: Deploy (OpenFin)
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r dist \
            gs://$BUCKET_OPENFIN/tag/${{ steps.vars.outputs.tag }}

      - name: Deploy (Launcher)
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r dist \
            gs://$BUCKET_LAUNCHER/tag/${{ steps.vars.outputs.tag }}

      - name: Build (OpenFin - Workspace)
        env:
          DOMAIN: https://openfin.prod.reactivetrader.com
          URL_PATH: /workspace
          VITE_BUILD_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          npm ci
          npm run build
        working-directory: src/workspace

      - name: Deploy (OpenFin - Workspace)
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r dist \
            gs://$BUCKET_OPENFIN/tag/${{ steps.vars.outputs.tag }}/workspace
        working-directory: src/workspace

      - name: Build (Finsemble)
        env:
          DOMAIN: https://finsemble.prod.reactivetrader.com
          VITE_BUILD_VERSION: ${{ steps.vars.outputs.tag }}
        run: npm run finsemble:build

      - name: Deploy (Finsemble)
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r dist \
            gs://$BUCKET_FINSEMBLE/tag/${{ steps.vars.outputs.tag }}
